# Ejercicios para controlar pandas

El animo de este documento es practicar una serie de mecanicas de pandas para interiorizarlas y dejar constancia del porque.

## Importamos un archivo y previsualizamos datos.

In [46]:
from pathlib import Path
import pandas as pd

Ruta = Path(r"C:\proyecto-faust\M02_Python_Librerias_Big_Data\UX_Material_Extra_Librerias\U10_ejercicios\consumo_horario_cliente.csv")
consumo = pd.read_csv(Ruta, sep = ";")
consumo.head()

              datetime  consumo_kwh  precio_kwh
0  2016-09-01 00:00:00        0.188    0.097510
1  2016-09-01 01:00:00        0.124    0.097756
2  2016-09-01 02:00:00        0.111    0.097713
3  2016-09-01 03:00:00        0.129    0.099275
4  2016-09-01 04:00:00        0.108    0.100793

## Comprobamos los datos que disponemos mediante .head(), .dtypes(), .info()

In [47]:
consumo.head()

              datetime  consumo_kwh  precio_kwh
0  2016-09-01 00:00:00        0.188    0.097510
1  2016-09-01 01:00:00        0.124    0.097756
2  2016-09-01 02:00:00        0.111    0.097713
3  2016-09-01 03:00:00        0.129    0.099275
4  2016-09-01 04:00:00        0.108    0.100793

In [9]:
consumo.dtypes

datetime        object
consumo_kwh    float64
precio_kwh     float64
dtype: object

In [48]:
consumo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2928 entries, 0 to 2927
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datetime     2928 non-null   object
 1   consumo_kwh  2928 non-null   float64
 2   precio_kwh   2928 non-null   float64
dtypes: float64(2), object(1)
memory usage: 68.8+ KB

## Cambiamos datetime a la categoria datetime, ya que esta reconocida como string: to_datetime()

In [49]:
consumo["datetime"] = pd.to_datetime(consumo["datetime"])

In [50]:
consumo.dtypes

datetime       datetime64[ns]
consumo_kwh           float64
precio_kwh            float64
dtype: object

## Extraemos el datos de la fecha, mediante dt.date, dt.hour, dt.year, dt.day_name() y le asignamos una columna adicional al DataFrame mediante .assign()

In [13]:
consumo["datetime"].dt.date

0       2016-09-01
1       2016-09-01
2       2016-09-01
3       2016-09-01
4       2016-09-01
           ...
2923    2016-10-09
2924    2016-10-09
2925    2016-10-09
2926    2016-10-09
2927    2016-10-09
Name: datetime, Length: 2928, dtype: object

In [14]:
consumo["datetime"].dt.year

0       2016
1       2016
2       2016
3       2016
4       2016
        ...
2923    2016
2924    2016
2925    2016
2926    2016
2927    2016
Name: datetime, Length: 2928, dtype: int32

In [16]:
consumo["datetime"].dt.day_name()

0       Thursday
1       Thursday
2       Thursday
3       Thursday
4       Thursday
          ...
2923      Sunday
2924      Sunday
2925      Sunday
2926      Sunday
2927      Sunday
Name: datetime, Length: 2928, dtype: object

In [52]:
consumo = consumo.assign( fecha = consumo["datetime"].dt.date, mes = consumo["datetime"].dt.month, dia = consumo["datetime"].dt.day_name())

In [53]:
consumo.head()

             datetime  consumo_kwh  precio_kwh       fecha  mes       dia
0 2016-09-01 00:00:00        0.188    0.097510  2016-09-01    9  Thursday
1 2016-09-01 01:00:00        0.124    0.097756  2016-09-01    9  Thursday
2 2016-09-01 02:00:00        0.111    0.097713  2016-09-01    9  Thursday
3 2016-09-01 03:00:00        0.129    0.099275  2016-09-01    9  Thursday
4 2016-09-01 04:00:00        0.108    0.100793  2016-09-01    9  Thursday

In [16]:
consumo = consumo.assign( coste = (consumo["consumo_kwh"] * consumo["precio_kwh"]).round(3))
consumo.head()

,datetime,consumo_kwh,precio_kwh,dia,fecha,mes,coste
0,2016-09-01 00:00:00,0.188,0.097510,Thursday,2016-09-01,9,0.018
1,2016-09-01 01:00:00,0.124,0.097756,Thursday,2016-09-01,9,0.012
2,2016-09-01 02:00:00,0.111,0.097713,Thursday,2016-09-01,9,0.011
3,2016-09-01 03:00:00,0.129,0.099275,Thursday,2016-09-01,9,0.013
4,2016-09-01 04:00:00,0.108,0.100793,Thursday,2016-09-01,9,0.011

## 1º Pregunta: ¿Cual es el consumo maximo que se ha registrado en los datos que tenemos? . max()

In [54]:
print(consumo["consumo_kwh"].max())

3.608

## 2º Pregunta: Indica los datos de la observacion que ha registrado el consumo maximo. Usaremos .loc() y una mascara booleana

In [19]:
consumo.loc[consumo["consumo_kwh"] == consumo["consumo_kwh"].max()]

,datetime,consumo_kwh,precio_kwh,dia,fecha,mes,coste
86,2016-09-04 14:00:00,3.608,0.104123,Sunday,2016-09-04,9,0.376

## 3º Pregunta: Filtrar horas con consumo inferior a 0.02 kWh. Usando .loc + masacara booleana.

In [55]:
consumo.loc[consumo["consumo_kwh"] < 0.02]

               datetime  consumo_kwh  precio_kwh       fecha  mes      dia
589 2016-12-27 13:00:00        0.010    0.131662  2016-12-27   12  Tuesday
590 2016-12-27 14:00:00        0.011    0.130844  2016-12-27   12  Tuesday
591 2016-12-27 15:00:00        0.010    0.130225  2016-12-27   12  Tuesday
592 2016-12-27 16:00:00        0.010    0.129591  2016-12-27   12  Tuesday
593 2016-12-27 17:00:00        0.011    0.135941  2016-12-27   12  Tuesday

## 4º Pregunta: Consumo promedio de los martes. Usando .loc + mascara booleana + seleccionando una columna + .mean()

In [31]:
consumo.loc[consumo["dia"] == "Tuesday"]["consumo_kwh"].mean()

np.float64(0.28270343137254905)

## 5º Pregunta: Precio_kwh promedio de los martes. Usando .loc + mascara booleana + seleccionando una columna + .mean()

In [32]:
consumo.loc[consumo["dia"] == "Tuesday"]["precio_kwh"].mean()

np.float64(0.1201746144362745)

## 6º Pregunta: Precio_kwh y consumo promedio de los martes y viernes. Usando .loc para localizar y .isin() para seleccionar martes y viernes, .groupby() por cada dia de la semana para generar un dataframe con unicamente estos dias + .mean()

In [34]:
consumo.loc[consumo["dia"].isin(["Tuesday","Friday"])].groupby("dia")[["precio_kwh", "consumo_kwh"]].mean()

         precio_kwh  consumo_kwh
dia
Friday     0.120325     0.285625
Tuesday    0.120175     0.282703

## 7º Pregunta: Precio_kwh y consumo promedio por mes. Usando .groupby() para agrupar por meses para generar un dataframe con unicamente estos dias + .mean()

In [56]:
consumo.groupby(consumo["mes"])[["precio_kwh", "consumo_kwh"]].mean()

     precio_kwh  consumo_kwh
mes
9      0.105438     0.350872
10     0.116826     0.293559
11     0.120675     0.304239
12     0.128199     0.331677

## 8º Pregunta: Cargamos otro fichero que dispone de costes de consumo de mayoristas. 1º lo cargamos, 2º comprobamos tipos de datos, 3º cambiamos categorias de datos si es necesario.

In [57]:
from pathlib import Path
import pandas as pd

Ruta_2 = Path(r"C:\proyecto-faust\M02_Python_Librerias_Big_Data\UX_Material_Extra_Librerias\U10_ejercicios\precio_md.csv")
consumo_extra = pd.read_csv(Ruta_2, sep = ";")
consumo_extra.head()

              datetime  preciomd_eurMw
0  2016-09-01 00:00:00           37.76
1  2016-09-01 01:00:00           36.00
2  2016-09-01 02:00:00           35.26
3  2016-09-01 03:00:00           35.26
4  2016-09-01 04:00:00           35.26

In [39]:
consumo_extra.dtypes

datetime           object
preciomd_eurMw    float64
dtype: object

In [58]:
consumo_extra["datetime"] = pd.to_datetime(consumo_extra["datetime"])

In [42]:
consumo_extra.dtypes

datetime          datetime64[ns]
preciomd_eurMw           float64
dtype: object

## 9º Pregunta: Vincular ambos dataframes para tener un unico DataFrame con todos los datos. Usando .merge() indicando los dataframes y el parametro *on* para seleccionar la columna.

In [59]:
consumo_cruce = pd.merge(consumo, consumo_extra, on = "datetime")

In [60]:
consumo_cruce.head()

,datetime,consumo_kwh,precio_kwh,fecha,mes,dia,preciomd_eurMw
0,2016-09-01 00:00:00,0.188,0.097510,2016-09-01,9,Thursday,37.76
1,2016-09-01 01:00:00,0.124,0.097756,2016-09-01,9,Thursday,36.00
2,2016-09-01 02:00:00,0.111,0.097713,2016-09-01,9,Thursday,35.26
3,2016-09-01 03:00:00,0.129,0.099275,2016-09-01,9,Thursday,35.26
4,2016-09-01 04:00:00,0.108,0.100793,2016-09-01,9,Thursday,35.26

## 10º Pregunta: Calcular una nueva columna con la diferencia entre el precio pagado por el consumidor cada hora y el precio de la electricidad diario. Primero sera necesario cambiar la unidades de conversion ya que uno es Kwh y el otro Mwh (/1000). Usaremos de nuevo .assign() con el calculo.

In [65]:
consumo_df = consumo_cruce.assign( dif_precio = (consumo_cruce["precio_kwh"] - (consumo_cruce["preciomd_eurMw"]/1000)).round(4))
consumo_df.head()

,datetime,consumo_kwh,precio_kwh,fecha,mes,dia,preciomd_eurMw,dif_precio
0,2016-09-01 00:00:00,0.188,0.097510,2016-09-01,9,Thursday,37.76,0.0598
1,2016-09-01 01:00:00,0.124,0.097756,2016-09-01,9,Thursday,36.00,0.0618
2,2016-09-01 02:00:00,0.111,0.097713,2016-09-01,9,Thursday,35.26,0.0625
3,2016-09-01 03:00:00,0.129,0.099275,2016-09-01,9,Thursday,35.26,0.0640
4,2016-09-01 04:00:00,0.108,0.100793,2016-09-01,9,Thursday,35.26,0.0655

## 11º Pregunta: Calcula el promedio de la diferencia de precios por mes. Usaremos .groupby() para agrupar los meses + seleccinando la columna dif_precio calcularemos la media con .mean()

In [66]:
consumo_df.groupby("mes")["dif_precio"].mean()

mes
9     0.061851
10    0.063991
11    0.064545
12    0.067712
Name: dif_precio, dtype: float64