Vamos a realizar una serie de operaciones y gestiones de datos en pandas para ir familiarizandonos.

En primer lugar, vamos a vincular un archivo con el que vamos a trabajar importando sus datos.

Importamos el archivo de la carpeta donde se ubican, indexamos y accederemos a las primeras 10 lineas para ver que se cargan adecuadamente.

In [2]:
from pathlib import Path
import numpy as np
import pandas as pd

Ruta_ej_1 = Path(r"C:\proyecto-faust\M02_Python_Librerias_Big_Data\UX_Material_Extra_Librerias\U10_ejercicios\consumo_horario_cliente.csv")
consumos = pd.read_csv(Ruta_ej_1, sep = ";")
consumos.head(10)

              datetime  consumo_kwh  precio_kwh
0  2016-09-01 00:00:00        0.188    0.097510
1  2016-09-01 01:00:00        0.124    0.097756
2  2016-09-01 02:00:00        0.111    0.097713
3  2016-09-01 03:00:00        0.129    0.099275
4  2016-09-01 04:00:00        0.108    0.100793
5  2016-09-01 05:00:00        0.115    0.101066
6  2016-09-01 06:00:00        0.120    0.105371
7  2016-09-01 07:00:00        0.120    0.107920
8  2016-09-01 08:00:00        0.378    0.106320
9  2016-09-01 09:00:00        0.130    0.108098

Lo primero vamos a cambiar el tipo de dato de las fechas a formato ***datetime*** para poder operar mejor en el futuro.

In [4]:
from pathlib import Path
import numpy as np
import pandas as pd

Ruta_ej_1 = Path(r"C:\proyecto-faust\M02_Python_Librerias_Big_Data\UX_Material_Extra_Librerias\U10_ejercicios\consumo_horario_cliente.csv")
consumos = pd.read_csv(Ruta_ej_1, sep = ";")
print(consumos["datetime"].dtype)
consumos["datetime"] = pd.to_datetime(consumos["datetime"])
print(consumos["datetime"].dtype)

object
datetime64[ns]

una vez podemos operar con la informacion de la columna con las funciones y atributos de las fechas, vamos a extraer algunas para poder asignarlas a la tabla y que sean mas operativas. Por ejemplo, extraeremos la fecha y la hora de la columna datetime y las asignaremos una columna nueva para fecha y hora

Utilizaremos ***.assign()*** para ello

In [11]:
from pathlib import Path
import numpy as np
import pandas as pd

Ruta_ej_1 = Path(r"C:\proyecto-faust\M02_Python_Librerias_Big_Data\UX_Material_Extra_Librerias\U10_ejercicios\consumo_horario_cliente.csv")
consumos = pd.read_csv(Ruta_ej_1, sep = ";")
consumos["datetime"] = pd.to_datetime(consumos["datetime"])
consumos = consumos.assign( fecha = consumos["datetime"].dt.date , hora = consumos["datetime"].dt.hour)
consumos.head()

             datetime  consumo_kwh  precio_kwh       fecha  hora
0 2016-09-01 00:00:00        0.188    0.097510  2016-09-01     0
1 2016-09-01 01:00:00        0.124    0.097756  2016-09-01     1
2 2016-09-01 02:00:00        0.111    0.097713  2016-09-01     2
3 2016-09-01 03:00:00        0.129    0.099275  2016-09-01     3
4 2016-09-01 04:00:00        0.108    0.100793  2016-09-01     4

Ahora vamos a realizar unas operaciones para comprobar conocimientos.

Fijándote en los ejemplos anteriores, ahora te vamos a pedir que escribas un código en el que asignes a nuestro DataFrame de consumos unas columnas con los siguientes valores:

- coste_eur : con el coste en euros de la energía consumida, multiplicando el consumo por el precio
- fecha : extrayendo la fecha de la columna datetime
- hora : extrayendo la hora de la columna datetime
- dia_semana : extrayendo el día de la semana de la columna datetime

In [19]:
from pathlib import Path
import numpy as np
import pandas as pd

Ruta_ej_1 = Path(r"C:\proyecto-faust\M02_Python_Librerias_Big_Data\UX_Material_Extra_Librerias\U10_ejercicios\consumo_horario_cliente.csv")
consumos = pd.read_csv(Ruta_ej_1, sep = ";")
consumos["datetime"] = pd.to_datetime(consumos["datetime"])
consumos = consumos.assign( coste_eur = lambda x: x["consumo_kwh"]*x["precio_kwh"])
consumos = consumos.assign( fecha = consumos["datetime"].dt.date ,
                           mes = consumos["datetime"].dt.month, 
                           dia_semana = consumos["datetime"].dt.day, 
                           hora = consumos["datetime"].dt.hour)
consumos.head()

,datetime,consumo_kwh,precio_kwh,coste_eur,fecha,mes,dia_semana,hora
0,2016-09-01 00:00:00,0.188,0.097510,0.018332,2016-09-01,9,1,0
1,2016-09-01 01:00:00,0.124,0.097756,0.012122,2016-09-01,9,1,1
2,2016-09-01 02:00:00,0.111,0.097713,0.010846,2016-09-01,9,1,2
3,2016-09-01 03:00:00,0.129,0.099275,0.012806,2016-09-01,9,1,3
4,2016-09-01 04:00:00,0.108,0.100793,0.010886,2016-09-01,9,1,4

Y ahora contestamos a mas cosas que nos piden en base a estos datos:

- ¿Cuál es el consumo máximo que se ha registrado en los datos que tenemos?

- Extrae los datos del día y hora en el que se ha registrado el mayor consumo.

- Filtra las horas con consumo inferior a 0.02 kwh

- ¿Puedes calcular el consumo promedio de los martes?

- ¿Y el precio promedio del kwh?

- ¿Serías capaz de calcular el consumo y precio promedio para los martes y los viernes usando una sola expresión? Pista: puedes utilizar el método isin() de una serie o columna para filtrar los días de la semana que caigan en martes o viernes, y utilizar groupby() para agregar después y calcular las medias.

- Calcula ahora los consumos y precios medios por mes.

In [37]:
#1º¿Cuál es el consumo máximo que se ha registrado en los datos que tenemos? Primero realizare una opcion que no me da lo que necesito
    # Utilizamos la funcion .sort_values para localizar los valores con consumos mas altos
        # Esta opcion no nos da unicamente el valor mas alto, sino que ordena los datos en funcion de sus valores

from pathlib import Path
import numpy as np
import pandas as pd

Ruta_ej_1 = Path(r"C:\proyecto-faust\M02_Python_Librerias_Big_Data\UX_Material_Extra_Librerias\U10_ejercicios\consumo_horario_cliente.csv")
consumos = pd.read_csv(Ruta_ej_1, sep = ";")
consumos["datetime"] = pd.to_datetime(consumos["datetime"])
consumos = consumos.assign(coste_eur = lambda x: x["consumo_kwh"]*x["precio_kwh"])
consumos = consumos.assign(fecha = consumos["datetime"].dt.date ,
                           mes = consumos["datetime"].dt.month, 
                           dia_semana = consumos["datetime"].dt.day, 
                           hora = consumos["datetime"].dt.hour)
max_consumo = consumos.sort_values(by="consumo_kwh", ascending =False)
max_consumo.head()

,datetime,consumo_kwh,precio_kwh,coste_eur,fecha,mes,dia_semana,hora
86,2016-09-04 14:00:00,3.608,0.104123,0.375675,2016-09-04,9,4,14
63,2016-09-03 15:00:00,3.233,0.099174,0.320629,2016-09-03,9,3,15
45,2016-09-02 21:00:00,3.056,0.111828,0.341746,2016-09-02,9,2,21
43,2016-09-02 19:00:00,2.937,0.106111,0.311648,2016-09-02,9,2,19
44,2016-09-02 20:00:00,2.890,0.109391,0.316141,2016-09-02,9,2,20

In [36]:
#1º¿Cuál es el consumo máximo que se ha registrado en los datos que tenemos? Hay 2 opciones
    # Aqui buscamos el valor .max() y luego extraemos la fila en una variable donde se ubica el valor mas alto, para poder referenciar los datos
        # Esta opcion localiza el valor mas alto, extraemos la informacion anexa y la exponemos como queremos.

from pathlib import Path
import numpy as np
import pandas as pd

Ruta_ej_1 = Path(r"C:\proyecto-faust\M02_Python_Librerias_Big_Data\UX_Material_Extra_Librerias\U10_ejercicios\consumo_horario_cliente.csv")
consumos = pd.read_csv(Ruta_ej_1, sep = ";")
consumos["datetime"] = pd.to_datetime(consumos["datetime"])
consumos = consumos.assign(coste_eur = lambda x: x["consumo_kwh"]*x["precio_kwh"])
consumos = consumos.assign(fecha = consumos["datetime"].dt.date ,
                           mes = consumos["datetime"].dt.month, 
                           dia_semana = consumos["datetime"].dt.day, 
                           hora = consumos["datetime"].dt.hour)
max_consumo = consumos["consumo_kwh"].max()
fila_max = consumos[consumos["consumo_kwh"] == max_consumo]
print(fila_max[["consumo_kwh", "dia_semana", "hora"]])

    consumo_kwh  dia_semana  hora
86        3.608           4    14